
# standard library imports
import ctypes as ct
from dataclasses import dataclass, InitVar
import datetime
from pathlib import Path
import shutil
import sys
import time

# 3rd party lib imports
import colorama  # pytest also uses this!
import numpy as np

# local imports
import GMAP
import GMAP.src.tools.coding_tools as GM_ct
import GMAP.src.tools.constants as GM_con
import GMAP.src.tools.exceptions as GM_ex
import GMAP.src.tools.print_tools as GM_pt
# from GMAP.src.tools.print_tools import devprint as dpr
import GMAP.src.tools.string_classes as GM_sc


@dataclass(repr=False, frozen=True)
class FileLocations(metaclass=GM_ct.Singleton):
    # Done automatically in the autogenerated __init__
    syspathcopy: tuple = tuple(sys.path[:])
    cmd: tuple = tuple(sys.argv)
    instr: tuple = tuple(sys.argv)
    start: int = time.perf_counter_ns()
    script_dir: Path = Path(GMAP.__file__).parent.resolve()
    cwd: Path = Path(".").resolve()
    now: datetime.datetime = datetime.datetime.now()
    refparfilename_hc: str = "reference_parameters.ref"

    # # These depend in some way on those above, so done in __post_init__:
    # callcommand: str = field(init=False)
    # now_str: str = field(init=False)
    # sourcedir_hc: Path = field(init=False)
    # mapdir_hc: Path = field(init=False)
    # # yes, could be done in __init__, but the default factory func is capable
    # # of throwing an error (which requires Printer), so we must only call it
    # # after Printer is initialized (which happens in __post_init__)
    # exec_os: str = field(init=False)
    # clib_extension: str = field(init=False)

    # These depend in some way on those above, so done in __post_init__:
    _callcommand: InitVar[str] = ""
    _instruction: InitVar[str] = ""
    _now_str: InitVar[str] = ""
    _sourcedir_hc: InitVar[Path] = Path()
    _mapdir_hc: InitVar[Path] = Path()
    # yes, could be done in __init__, but the default factory func is capable
    # of throwing an error (which requires Printer), so we must only call it
    # after Printer is initialized (which happens in __post_init__)
    _exec_os: InitVar[str] = ""
    _clib_extension: InitVar[str] = ""

    def __post_init__(self, *args):
        colorama.just_fix_windows_console()  # Enable colors in program output!

        cmd = (Path(self.cmd[0]).name,) + self.cmd[1:]
        try:  # if the first bit is a file name
            instr = (Path(self.instr[0]).name,) + self.instr[1:]
        except Exception:
            instr = self.instr

        obset = object.__setattr__
        obset(self, "_callcommand", " ".join(cmd))
        obset(self, "_instruction", " ".join(instr))
        obset(self, "_now_str", self.now.strftime("%Y-%m-%d_%H-%M-%S"))
        obset(self, "_sourcedir_hc", self.script_dir / "sourcefiles")
        obset(self, "_mapdir_hc", self.script_dir / "maps")

        # printer needs to know some things (like current date) as to
        # properly print. (date influences crash file name)
        GM_pt.Printer(self)  # initialize the printer!

        obset(self, "_exec_os", find_exec_os())
        obset(self, "_clib_extension", GM_con.clib_ext_dict[self._exec_os])

    @GM_ct.SingletonProperty
    def callcommand(self):
        return self._callcommand

    @GM_ct.SingletonProperty
    def instruction(self):
        return self._instruction

    @GM_ct.SingletonProperty
    def now_str(self):
        return self._now_str

    @GM_ct.SingletonProperty
    def sourcedir_hc(self):
        return self._sourcedir_hc

    @GM_ct.SingletonProperty
    def mapdir_hc(self):
        return self._mapdir_hc

    @GM_ct.SingletonProperty
    def exec_os(self):
        return self._exec_os

    @GM_ct.SingletonProperty
    def clib_extension(self):
        return self._clib_extension


def find_exec_os():
    """Determines which os the system is running on.

    Returns
    -------
    exec_os : str
        The platform on which the program runs. Might be 32- or 64 bit Windows,
        Linux, or MacOS.
    """

    exec_os = None

    if sys.platform == "win32":
        bits = ct.sizeof(ct.c_void_p)*8
        if bits == 32:
            exec_os = "Win32bit"
        elif bits == 64:
            exec_os = "Win64bit"
        else:
            GM_pt.Printer.warning(
                "\nEnvironment was determined to be windows, but it is "
                "neither a"
                f" 32, nor 64 bit version. It appears to be {bits} bit. Please"
                " contact the developers to solve this.",
                "howtogethere", True, GMAPerrclass=GM_ex.GmapOSError
            )
    elif sys.platform == "darwin":
        exec_os = "MacOS"
    elif sys.platform == "linux":
        exec_os = "Linux"
    else:
        GM_pt.Printer.warning(
            f"\nexecuting OS not recognised... sys.platform = {sys.platform}. "
            "Please contact the developers to solve this. ",
            "howtogethere", True, GMAPerrclass=GM_ex.GmapOSError
        )

    return exec_os


def get_file(
    dir_parname, file_parname, dir_hc, files_hc,
    cmd_pardict, pardicts=[], parfilelocs=[]
):
    """Determine the path to a file given all input sources

    As there are 4 places that might store information regarding the
    file's path, each of which can contain 2 bits of information, which
    don't both have to be there, the dicision tree is somewhat complex,
    see the devnotes file for a table on what parameters are used in
    which case.

    The naively found path is returned, but not checked for existence or
    validity. That is a separate step the caller should invoke.

    .. seealso::
        :func:`get_bare_file`
            Does the same, but for files which are not assumed relative
            to a path stored in another parameter.
        :func:`try_file`
            Checks the existence and file-ness of a given path.
        :func:`check_file_readability`
            Checks whether the given file can actually be read.

    Parameters
    ----------
    dir_parname : str
        The name of the parameter storing the directory path to which
        the desired parameter path is assumed relative to.
    file_parname : str
        The name of the parameter storing the path of the desired file.
    dir_hc : `pathlib.Path`
        In case the parameter in `dir_parname` does not exist in any of
        the given inputs, use this one.
    files_hc : list of `pathlib.Path`
        In case the parameter in `file_parname` does not exist in any of
        the given inputs, use this one.
    cmd_pardict : dict
        The dict storing all parameter choices from the command line.
    pardicts : list of dicts, default=[]
        All dicts storing parameter choices, ordered by importance - if
        a parameter is found in a dict earlier in the list, don't use
        any occurences later in the list.
    parfilelocs : list of `pathlib.Path`, default=[]
        The paths to the files whose contents are in the pardicts list,
        in the same order.

    Returns
    -------
    names : list of `pathlib.Path`
        The path to the desired file.
    file_is_hc : bool
        Whether the dir_hc/file_hc fallback had to be used.
    """

    file_is_hc = False
    dicts = [cmd_pardict]
    flocs = [FileLocations.cwd]

    for dict_, floc in zip(pardicts, parfilelocs):
        if dict_:
            dicts.append(dict_)
            flocs.append(floc.parent)

    for ix, (dict_, floc) in enumerate(zip(dicts, flocs)):
        if dir_parname in dict_:
            dirname = floc / dict_[dir_parname][0]
            for dict_ in dicts[ix:]:
                if file_parname in dict_:
                    filenames = dict_[file_parname]
                    break
            else:
                filenames = files_hc
            break
        elif file_parname in dict_:
            dirname = floc
            filenames = dict_[file_parname]
            break
    else:
        dirname = dir_hc
        filenames = files_hc
        file_is_hc = True

    names = [dirname / name for name in filenames]

    return names, file_is_hc


def get_bare_file(
    file_parname, files_hc, floc_hc, cmd_pardict, pardicts=None,
    parfilelocs=None
):
    """Determine the path to a file given all input sources

    There are 4 places that might store information regarding the file's
    path, which should be considered in a set order.

    The naively found path is returned, but not checked for existence or
    validity. That is a separate step the caller should invoke.

    .. seealso::
        :func:`get_file`
            Does the same, but for files which are assumed relative to a
            path stored in another parameter.
        :func:`try_file`
            Checks the existence and file-ness of a given path.
        :func:`check_file_readability`
            Checks whether the given file can actually be read.

    Parameters
    ----------
    file_parname : str
        The name of the parameter storing the path of the desired file.
    file_hc : list of `pathlib.Path`
        In case the parameter in `file_parname` does not exist in any of
        the given inputs, use this one.
    floc_hc : `pathlib.Path`
        The base location from where the paths should be taken.
    cmd_pardict : dict
        The dict storing all parameter choices from the command line.
    pardicts : list of dicts, default=[]
        All dicts storing parameter choices, ordered by importance - if
        a parameter is found in a dict earlier in the list, don't use
        any occurences later in the list.
    parfilelocs : list of `pathlib.Path`, default=[]
        The paths to the files whose contents are in the pardicts list,
        in the same order.

    Returns
    -------
    names : list of `pathlib.Path`
        The path to the desired file
    """

    if pardicts is None:
        pardicts = []
    if parfilelocs is None:
        parfilelocs = []

    dicts = [cmd_pardict]
    flocs = [FileLocations.cwd]

    for dict_, floc in zip(pardicts, parfilelocs):
        if dict_:
            dicts.append(dict_)
            flocs.append(floc.parent)

    for dict_, floc in zip(dicts, flocs):
        if file_parname in dict_:
            names = [floc / name for name in dict_[file_parname]]
            break
    else:
        names = [floc_hc / name for name in files_hc]

    return names


def get_def_parfile(
    cmd_pardict, in_parfile=None, in_pardict=None
):
    """
    Given the parameter information on the command line, and,
    optionally, an input parameters file and its contents, finds out the
    location of the default parameters file.

    If the user specified anything (either the sourcedir or the name of
    the default parameter file), the program checks that. If nothing is
    present there or if it isn't a file, an error is raised, and the
    program quits.

    Parameters
    ----------
    cmd_pardict : dict
        The dict storing the parameter choices from the command line.
    in_parfile : `pathlib.Path` or NoneType, default=None
        The filename of the input parameter file.
    in_pardict : dict, default={}
        The parameters supplied in the input parameter file.
    """

    files = FileLocations
    if in_pardict is None:
        in_pardict = {}

    name, file_is_hc = get_file(
        "source_directory", "default_parameter_filename",
        files.sourcedir_hc, [files.refparfilename_hc],
        cmd_pardict, [in_pardict], [in_parfile]
    )

    file_found = try_file(name[0])

    if not file_found:
        GM_pt.Printer.warning(
            f"\nThe requested default parameter file {name} could not be "
            "found, or is not a file. "
            "Please make sure you specified it correctly.\n",
            "SU_FH_1", True, GMAPerrclass=GM_ex.GmapFileNotFoundError
        )

    # We need a file to check if the default file is complete (AIM did this
    # using hard-coded parameters)
    if file_is_hc:
        check_file_found = file_found
    else:
        name = files.sourcedir_hc / files.refparfilename_hc
        check_file_found = try_file(name)
        if not check_file_found:
            GM_pt.Printer.warning(
                "\nThe requested default parameter file requires the presence "
                f"of the file {name}, but this file could not be found. "
                "Please make sure you specified it correctly.\n",
                "SU_FH_2", True, GMAPerrclass=GM_ex.GmapFileNotFoundError
            )

    return file_found


def try_file(fname):
    """Checks if the given location exists, and is a file.

    If so, returns pathlib.Path.resolve(location), otherwise, returns
    None. Does not check whether the file is of a readable format.

    .. seealso::
        :func:`check_file_readability`
            Checks whether the given file can actually be read.

    Parameters
    ----------
    fname : `pathlib.Path`
        The path to check

    Returns
    -------
    fname : `pathlib.Path` or None
        The resolved path, or, if the input doesn't exist, None.
    """

    if fname.is_file():
        return fname.resolve()
    else:
        return None


def check_file_readability(fname, doprint=True, doquit=True):
    """Checks if a given file can be read.

    If not, lets GM_pt.Printer raise the appropriate error.

    .. seealso::
        :func:`try_file`
            Checks the existence and file-ness of a given path.

    Parameters
    ----------
    fname : `pathlib.Path`
        The path to the file to check.
    doprint : bool, default=True
        Whether failure of this test should be reported to the user.
    doquit : bool, default=True
        Whether the program should raise an error if the file fname is
        not readable to the program.

    Returns
    -------
    is_readable : bool
        Whether the file is readable.
    """

    try:
        with open(fname, 'r', encoding='utf-8') as file:
            for _ in file:
                pass
    except UnicodeDecodeError:
        if doprint:
            GM_pt.Printer.warning(
                f"\n The file {fname} is of the wrong type, please make sure "
                "it is a plain text file. ",
                "SU_FH_3", doquit, GMAPerrclass=GM_ex.GmapUnicodeDecodeError
            )
        return False
    return True


def write_output(run_pars, framenum, outputs):
    """Write the output for a single frame to files.

    Writes all outputs - all (requested) datastructures in all
    (requested) formats.

    Parameters
    ----------
    run_pars : :class:`~GMAP.src.tools.parameter_parser.RunPars`
        The 'main' RunPars instance containing all the basic
        run-defining parameters.
    framenum : int
        The number of the frame currently being written
    outputs : dict of str: `np.ndarray` pairs
        The outputs the program is requested to generate. Currently
        contains hamiltonian and dipole arrays.
    """

    framenum_arr = np.array([framenum], dtype='float32')

    if "ham" in run_pars.output_data:
        hamiltonian = outputs["hamiltonian"]
        hamiltonian *= run_pars.hamiltonian_multiplier
        reshaped = hamiltonian[np.triu_indices_from(hamiltonian)]
        write_single(
            run_pars, framenum, framenum_arr,
            run_pars.output_hamiltonian_filename, reshaped
        )

    if "ene" in run_pars.output_data:
        energies = outputs["energies"]
        energies *= run_pars.energies_multiplier
        write_single(
            run_pars, framenum, framenum_arr,
            run_pars.output_energies_filename, energies
        )

    if "dip" in run_pars.output_data:
        dipoles = outputs["dipoles"]
        dipoles *= run_pars.dipoles_multiplier
        reshaped = dipoles.T.flatten()
        write_single(
            run_pars, framenum, framenum_arr,
            run_pars.output_dipole_filename, reshaped
        )

    if "ram" in run_pars.output_data:
        raman = outputs["raman"]
        raman *= run_pars.raman_multiplier
        reshaped = raman.T.flatten()
        write_single(
            run_pars, framenum, framenum_arr,
            run_pars.output_raman_filename, reshaped
        )

    if "pos" in run_pars.output_data:
        positions = outputs["positions"]
        positions *= run_pars.positions_multiplier
        reshaped = positions.T.flatten()
        write_single(
            run_pars, framenum, framenum_arr,
            run_pars.output_positions_filename, reshaped
        )

    if "dbp" in run_pars.output_data:
        doublepos = outputs["doublepos"]
        doublepos *= run_pars.doublepos_multiplier
        reshaped = doublepos.T.flatten()
        write_single(
            run_pars, framenum, framenum_arr,
            run_pars.output_doublepos_filename, reshaped
        )


def write_single(run_pars, framenum, framenum_arr, fname, data):
    """Write a single datastructure to files of given name.

    Writes to all different requested formats at once.

    Parameters
    ----------
    run_pars : :class:`~GMAP.src.tools.parameter_parser.RunPars`
        The 'main' RunPars instance containing all the basic
        run-defining parameters.
    framenum : int
        The number of the frame currently being written
    framenum_arr : `np.ndarray`
        The framenumber as float32 array, ready for binary writing
    fname : `pathlib.Path`
        The name + location of the file to which to write. This filename
        should not include the extension!
    data : `np.ndarray`
        The data that should be written to the file.
    """

    if "bin" in run_pars.output_format:
        with open(fname.parent / f"{fname.name}.bin", "ab") as fhand:
            framenum_arr.tofile(fhand)  # write frame number
            data.tofile(fhand)  # write data itself (Ham or Dip or ...)

    if "txt" in run_pars.output_format:
        with open(
            fname.parent / f"{fname.name}.txt", "a", encoding='utf-8'
        ) as fhand:
            fhand.write(f"{framenum} ")  # write frame number
            # data = np.round(data, decimals=6)
            decs = 6
            data = np.rint(data*10**decs)/(10**decs)
            # write data itself (Ham or Dip or ...)
            # data.tofile(fhand, sep=" ", format="%#.6g")
            data.tofile(fhand, sep=" ")
            fhand.write("\n")


def clear_output(run_pars):
    """Prepare an empty file for each output

    If files already exist, clears them. If not, creates them.

    Parameters
    ----------
    run_pars : :class:`~GMAP.src.tools.parameter_parser.RunPars`
        The 'main' RunPars instance containing all the basic
        run-defining parameters.
    """

    if "ham" in run_pars.output_data:
        clear_single(run_pars, run_pars.output_hamiltonian_filename)
    if "ene" in run_pars.output_data:
        clear_single(run_pars, run_pars.output_energies_filename)
    if "dip" in run_pars.output_data:
        clear_single(run_pars, run_pars.output_dipole_filename)
    if "ram" in run_pars.output_data:
        clear_single(run_pars, run_pars.output_raman_filename)
    if "pos" in run_pars.output_data:
        clear_single(run_pars, run_pars.output_positions_filename)
    if "dbp" in run_pars.output_data:
        clear_single(run_pars, run_pars.output_doublepos_filename)


def clear_single(run_pars, fname):
    """Clears any file if it exists prior to writing

    A file shouldn't contain anything when first appended to.

    Parameters
    ----------
    run_pars : :class:`~GMAP.src.tools.parameter_parser.RunPars`
        The 'main' RunPars instance containing all the basic
        run-defining parameters.
    fname : `pathlib.Path`
        The name + location of the file to which to write. This filename
        should not include the extension!
    """

    if "bin" in run_pars.output_format:
        with open(fname.parent / f"{fname.name}.bin", "wb") as _:
            pass
    if "txt" in run_pars.output_format:
        with open(fname.parent / f"{fname.name}.txt", "w") as _:
            pass


def write_legend(run_pars, system):
    """Writes the contents of the legend file.

    The purpose of the legend file is to specify what the other output
    files contain. Each file saves some property of the oscillators of
    the system, but nowhere can you find what oscillators are actually
    in the file. This file solves that. To make sure the contents are
    valuable for all kinds of systems/oscillators, each map can specify
    how it wants its oscillator denoted in this file (and general print
    outputs of the program) using the function GM_str_osc in the file
    main.py of the map.

    Parameters
    ----------
    run_pars : :class:`~GMAP.src.tools.parameter_parser.RunPars`
        The 'main' RunPars instance containing all the basic
        run-defining parameters.
    system : :class:`~GMAP.src.tools.system_reader.System`
        The class containing all the information on the system of the
        MD trajectory.
    """

    with open(run_pars.output_legend_filename, "w", encoding='utf-8') as fhand:
        for oscix, oscillator in enumerate(system.oscillators):
            fhand.write(f"at index {oscix}: {oscillator}\n")


def write_parameter_file(
    ref_pars, run_pars, system, cmd_pars, in_pars, def_pars
):
    """Save the parameters of the current run to a file so the run can
    be repeated.

    Parameters
    ----------
    ref_pars : :class:`RefPars`
        Contains all available parameters from GMAP itself
        (not map-specific)
    run_pars : :class:`~GMAP.src.tools.parameter_parser.RunPars`
        The 'main' RunPars instance containing all the basic
        run-defining parameters.
    system : :class:`~GMAP.src.tools.system_reader.System`
        The class containing all the information on the system of the
        MD trajectory.
    cmd_pars : :class:`RawPars`
        Contains any parameter choices made on the command line
    in_pars : :class:`RawPars`
        Contains any parameter choices made in the input parameter file
    def_pars : :class:`RawPars` or :class:`RefPars`
        Contains all default parameter choices. Might be ref_pars, might
        be from a separate default parameters file.
    """

    # initialize file
    with open(
        run_pars.output_parameter_filename, "w", encoding='utf-8'
    ) as outfhand:
        # write GMAP parameters
        with open(ref_pars.fname, "r") as reffhand:
            write_single_parameter_source(
                reffhand, run_pars, outfhand, "GMAP", cmd_pars, in_pars,
                def_pars)

        # write parameters of all active singles maps
        for singles_map in run_pars.requested_mapdict.values():
            with open(
                singles_map.directory / "parameters.ref", "r"
            ) as reffhand:
                write_single_parameter_source(
                    reffhand, singles_map.run_pars, outfhand, singles_map.name,
                    singles_map.cmd_pars, singles_map.in_pars,
                    singles_map.def_pars)

        # write parameters of all active pairs maps.
        for pairs_map in run_pars.requested_pairmapdict.values():
            with open(
                pairs_map.directory / "parameters.ref", "r"
            ) as reffhand:
                write_single_parameter_source(
                    reffhand, pairs_map.run_pars, outfhand, pairs_map.name,
                    pairs_map.cmd_pars, pairs_map.in_pars, pairs_map.def_pars)


def write_single_parameter_source(
    reffhand, run_pars, outfhand, sourcename, cmd_pars, in_pars, def_pars
):
    """Save the parameters of a single source to a file so the run can
    be repeated.

    Parameters
    ----------
    reffhand : `_io.TextIOWrapper`
        The reference parameter file handle which contains all
        parameters that should be written.
    run_pars : :class:`~GMAP.src.tools.parameter_parser.RunPars`
        The 'main' RunPars instance containing all the basic
        run-defining parameters.
    outfhand : `_io.TextIOWrapper`
        The output parameter file handle to which all parameters should
        be written.
    sourcename : str
        The name of the source (GMAP or name of map) whose parameters
        should be saved.
    cmd_pars : :class:`RawPars`
        Contains any parameter choices made on the command line
    in_pars : :class:`RawPars`
        Contains any parameter choices made in the input parameter file
    def_pars : :class:`RawPars` or :class:`RefPars`
        Contains all default parameter choices. Might be ref_pars, might
        be from a separate default parameters file.
    """

    write_parameter_header(sourcename, outfhand)

    # A select few parameters can be multiline
    sp_choices = []
    sp_prname = None

    for line in reffhand:
        # Find name of parameter on this line
        linelist = line.split("#")
        parname = linelist[0].split("[")[0].split("(")[0]
        # find full (source-including) parameter name
        prparname = get_full_parameter_name(parname, sourcename)

        # if this line does not contain a parameter
        if not hasattr(run_pars, parname):
            outfhand.write(line)
            continue

        # we expect all occurences of the same parameter to be back-to-back
        # in a parameter file. So if we've got more lines availabe that
        # haven't been printed yet, print them now.
        if len(sp_choices) > 0 and sp_prname != prparname:
            while len(sp_choices) > 0:
                choice = sp_choices.pop(0)
                write_parameter_line(
                    outfhand, sp_prname, choice, [])
            sp_prname = None

        # write all parameters that are not expected to occur multiple times
        sp_choices, sp_prname = write_parameter_line_main(
            run_pars, parname, prparname, sp_prname, outfhand, linelist,
            cmd_pars, in_pars, def_pars)

    outfhand.write("\n\n\n")


def write_parameter_header(sourcename, outfhand):
    """Write the header of the next parameter source to the output file.

    Parameters
    ----------
    sourcename : str
        The name of the source (GMAP or name of map) whose parameters
        should be saved.
    outfhand : `_io.TextIOWrapper`
        The output parameter file handle to which all parameters should
        be written.
    """

    header = GM_sc.Header(
        f"\n{sourcename}\n", linemode="oulrc", padding=3, corner_char="╔╗╚╝",
        overline_char="═", underline_char="═", left_char="║", right_char="║"
    ).cs.change_color("white")
    header = "# " + "\n# ".join(header.split("\n"))
    outfhand.write(f"\n{header}\n")


def get_full_parameter_name(parname, sourcename):
    """Figure out what name the parameter should be saved as.

    GMAP parameters should be written/saved as-is, while map paramters
    should be preceded by the map name.

    Parameters
    ----------
    parname : str
        The parameter that we'd like to write to file.
    sourcename : str
        The name of the source (GMAP or name of map) whose parameters
        should be saved.
    """

    if sourcename == "GMAP":
        return parname
    else:
        return sourcename + "." + parname


def write_parameter_line_main(
    run_pars, parname, prparname, sp_prname, outfhand, linelist,
    cmd_pars, in_pars, def_pars
):
    """Save the parameters of a single source to a file so the run can
    be repeated.

    Parameters
    ----------
    run_pars : :class:`~GMAP.src.tools.parameter_parser.RunPars`
        The 'main' RunPars instance containing all the basic
        run-defining parameters.
    parname : str
        The parameter that we'd like to write to file.
    prparname : str
        The full name of the parameter (possibly including source name)
        that we'd like to write to file.
    sp_prname : The full name of the special parameter that we treated
        last.
    outfhand : `_io.TextIOWrapper`
        The output parameter file handle to which all parameters should
        be written.
    linelist : list of str
        The line from the reference parameter file, split on "#".
    cmd_pars : :class:`RawPars`
        Contains any parameter choices made on the command line
    in_pars : :class:`RawPars`
        Contains any parameter choices made in the input parameter file
    def_pars : :class:`RawPars` or :class:`RefPars`
        Contains all default parameter choices. Might be ref_pars, might
        be from a separate default parameters file.
    """

    # parname structures for special parameters
    all_inf_pars = set((
        "influencers_whitelist", "influencers_blacklist", "influencers_file",
        "influencers_select_atoms"))
    all_unit_ends = set(("_units", "_multiplier"))

    choice = getattr(run_pars, parname)
    # Write parameters that are allowed to occur multiple times
    if (
        isinstance(choice, list)
        and len(choice) > 0  # so we write entire parameter on first occurence
        and isinstance(choice[0], list)
    ):
        if prparname != sp_prname:
            sp_choices = choice[:]
            sp_prname = prparname
        choice = sp_choices.pop(0)
        write_parameter_line(outfhand, prparname, choice, linelist)
        return sp_choices, sp_prname

    # Write C-library parameters
    # ( prparname instead of parname to make sure we only look at GMAP own's
    #   parameters
    elif prparname.endswith("_clib_file"):
        choice = str(choice.resolve())
        choice = "_".join(choice.split("_")[:-1])
        write_parameter_line(outfhand, prparname, choice, linelist)

    # Write influencer parameters
    elif prparname.startswith("influencers_"):
        if prparname != "influencers_whitelist":
            return [], sp_prname
        write_parameter_intersect(
            outfhand, prparname, cmd_pars, in_pars, def_pars, all_inf_pars,
            linelist)

    # Write unit-specifying parameters
    elif (
        any(prparname.startswith(item) for item in (
            "hamiltonian_", "energies_", "dipoles_", "raman_",
            "positions_", "doublepos_"))
        and any(prparname.endswith(item) for item in all_unit_ends)
    ):
        # ignore the units, only print multiplier (in case of defpars)
        if prparname.endswith("_units"):
            return [], sp_prname
        parnames = [prparname.split("_")[0] + item for item in all_unit_ends]
        write_parameter_intersect(
            outfhand, prparname, cmd_pars, in_pars, def_pars, parnames,
            linelist)

    # Write 'normal' / other parameters.
    else:
        # now, all special multiline-parameters have been taken care of,
        # so continue to print this new one.
        write_parameter_line(outfhand, prparname, choice, linelist)
    return [], sp_prname


def write_parameter_line(outfhand, prparname, choice, linelist):
    """Write a single parameter line to the output file.

    Parameters
    ----------
    outfhand : `_io.TextIOWrapper`
        The output parameter file handle to which all parameters should
        be written.
    prparname : str
        The full name of the parameter (possibly including source name)
        that we'd like to write to file.
    choice : any
        The choice as saved in run_pars for this parameter
    linelist : list of str
        The line from the reference parameter file, split on "#".
    """

    if isinstance(choice, list):
        if len(choice) == 0:
            choice = ["None"]
        choice = " ".join([str(item) for item in choice])

    outfhand.write(f"{prparname:<40}  {choice}  ")
    if len(linelist) > 1:
        outfhand.write("#" + "#".join(linelist[1:]))
    else:
        outfhand.write("\n")


def write_parameter_intersect(
    outfhand, prparname, cmd_pars, in_pars, def_pars, parnames, linelist
):
    """Save a single parameter. This one has multiple options in the
    reference file, of which only one may be written.

    Each possible parameter source is searched for all valid parameters.
    The first one found will be the one written to file.

    Parameters
    ----------
    outfhand : `_io.TextIOWrapper`
        The output parameter file handle to which all parameters should
        be written.
    prparname : str
        The full name of the parameter (possibly including source name)
        that we'd like to write to file.
    cmd_pars : :class:`RawPars`
        Contains any parameter choices made on the command line
    in_pars : :class:`RawPars`
        Contains any parameter choices made in the input parameter file
    def_pars : :class:`RawPars` or :class:`RefPars`
        Contains all default parameter choices. Might be ref_pars, might
        be from a separate default parameters file.
    parnames : iterable
        The parameter names that are an acceptable substitute for
        prparname when looking through the source
    linelist : list of str
        The line from the reference parameter file, split on "#".
    """

    for parsource in (cmd_pars, in_pars):
        intersection = set(parnames).intersection(parsource.choices)
        if len(intersection) > 0:
            parameter = intersection.pop()
            write_parameter_line(
                outfhand, parameter, parsource.choices[parameter], [])
            return
    # if no source mentions any influencers
    write_parameter_line(
        outfhand, prparname, def_pars.choices[prparname], linelist)


def merge_files(run_pars):
    """Merge output files from multiple runs.

    Log files from child-runs are pasted to the end of the one of the
    original run (and the originals removed). Parameter files from child
    runs are just removed. Output files are, just as log files, copied
    to the end of the corresponding parent-run file.

    Parameters
    ----------
    run_pars : :class:`~GMAP.src.tools.parameter_parser.RunPars`
        The 'main' RunPars instance containing all the basic
        run-defining parameters.
    """

    data_to_fname = {
        "ham": "output_hamiltonian_filename",
        "dip": "output_dipole_filename",
        "ene": "output_energies_filename",
        "pos": "output_positions_filename",
        "dbp": "output_doublepos_filename",
        "ram": "output_raman_filename"
    }

    # merge log files
    dest_fname = run_pars.log_filename
    with open(dest_fname, "a", encoding='utf-8') as fdst:
        for cpu_num in range(run_pars.number_cores):
            source_fname = fname_to_tempname("logfile", run_pars, cpu_num)
            with open(source_fname, encoding='utf-8') as fsrc:
                shutil.copyfileobj(fsrc, fdst)
            Path(source_fname).unlink()

    # remove parameter files
    for cpu_num in range(run_pars.number_cores):
        parfile = fname_to_tempname("parfile", run_pars, cpu_num)
        Path(parfile).unlink()

    # merge all requested data output files
    for output_type in run_pars.output_format:
        mode = "b" if output_type == "bin" else ""
        suff = ".bin" if output_type == "bin" else ".txt"
        encoding = None if output_type == "bin" else "utf-8"
        for treat_data in run_pars.output_data:
            dest_fname = getattr(run_pars, data_to_fname[treat_data])
            with open(
                str(dest_fname) + suff, "w" + mode, encoding=encoding
            ) as fdst:
                for cpu_num in range(run_pars.number_cores):
                    source_fname = str(fname_to_tempname(
                        treat_data, run_pars, cpu_num)) + suff
                    with open(
                        source_fname, "r" + mode, encoding=encoding
                    ) as fsrc:
                        shutil.copyfileobj(fsrc, fdst)
                    Path(source_fname).unlink()

    # after deleting all files, make sure to delete tempdir!
    if any(run_pars.parrun_directory.iterdir()):
        GM_pt.Printer.warning(
            f"The directory {run_pars.parrun_directory} was temporarily made "
            "by GMAP. However, it can now not safely be removed. Please take "
            "a look at this directory yourself.",
            "PF_MD_1", GMAPerrclass=GM_ex.GmapValueError)
    else:  # directory is empty, it can safely be removed
        run_pars.parrun_directory.rmdir()


def fname_to_tempname(output_data, run_pars, CPU):
    """Generate the temporary file names used for parallel threads based
    on required file type, a run_pars instance, and CPU number.

    Parameters
    ----------
    output_data : str
        ham/dip/ene/etc
    run_pars : dict or :class:`~GMAP.src.tools.parameter_parser.RunPars`
        The 'main' RunPars instance containing all the basic
        run-defining parameters. If this is not available (due to
        certain module functions not allowing custom classes), this
        parameter should contain the output of run_pars.parallel_dict.
    CPU : int
        The number of the CPU responsible for the file location created
        by this function.

    Returns
    -------
    fpath : `pathlib.Path`
        The filename that should be used for the requested function.
    """

    data_to_fname = {
        "ham": "output_hamiltonian_filename",
        "dip": "output_dipole_filename",
        "ene": "output_energies_filename",
        "pos": "output_positions_filename",
        "dbp": "output_doublepos_filename",
        "ram": "output_raman_filename",
        "parfile": "output_parameter_filename",
        "logfile": "log_filename"
    }

    if isinstance(run_pars, dict):
        parent = run_pars["parrun_directory"]
        path = run_pars[data_to_fname[output_data]]
    else:
        parent = run_pars.parrun_directory
        path = getattr(run_pars, data_to_fname[output_data])

    return parent / f"{path.stem}_CPU{CPU}{path.suffix}"
